from __future__ import annotations

import argparse
import sys
from pathlib import Path

SHARED_DIR = Path(__file__).resolve().parents[1] / "shared"
if str(SHARED_DIR) not in sys.path:
    sys.path.append(str(SHARED_DIR))

from feature_utils import DEFAULT_EXPERIMENTS, save_json, write_csv_rows
from retrieval_core import RetrievalEngine


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run top-k bird-image retrieval using the SQLite-backed CBIR pipeline."
    )
    parser.add_argument(
        "--db-path",
        default="data/features/cbir_features.sqlite",
        help="SQLite database generated by build_feature_db.py.",
    )
    parser.add_argument(
        "--processed-root",
        default="data/processed",
        help="Processed image root used to resolve gallery references.",
    )
    parser.add_argument(
        "--experiment-name",
        choices=tuple(DEFAULT_EXPERIMENTS.keys()),
        default="handcrafted_only",
        help="Experiment configuration registered in the experiments table.",
    )
    parser.add_argument(
        "--query-image-id",
        type=int,
        default=0,
        help="Existing gallery image_id to use as the query.",
    )
    parser.add_argument(
        "--query-image-path",
        default="",
        help="External query image path. Used when --query-image-id is not provided.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of ranked results to return.",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Execution device for the optional CNN descriptor when the query is external.",
    )
    parser.add_argument(
        "--output-csv",
        default="outputs/retrieval/topk_results.csv",
        help="CSV path for the ranked retrieval output.",
    )
    parser.add_argument(
        "--output-json",
        default="outputs/retrieval/topk_results.json",
        help="JSON path for the full retrieval payload.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    query_image_id = int(args.query_image_id) if int(args.query_image_id) > 0 else None
    query_image_path = str(args.query_image_path).strip() or None

    engine = RetrievalEngine(
        db_path=Path(args.db_path),
        processed_root=Path(args.processed_root),
        device=args.device,
    )
    try:
        payload = engine.run_retrieval(
            experiment_name=args.experiment_name,
            top_k=args.top_k,
            query_image_id=query_image_id,
            query_image_path=query_image_path,
            persist=True,
        )
    finally:
        engine.close()

    rows = [
        {
            "rank": row["rank"],
            "image_id": row["image_id"],
            "species_id": row["species_id"],
            "species_name": row["species_name"],
            "processed_relative_path": row["processed_relative_path"],
            "fused_score": row["fused_score"],
            "per_feature_scores_json": row["per_feature_scores"],
        }
        for row in payload["results"]
    ]
    write_csv_rows(
        Path(args.output_csv).resolve(),
        rows,
        [
            "rank",
            "image_id",
            "species_id",
            "species_name",
            "processed_relative_path",
            "fused_score",
            "per_feature_scores_json",
        ],
    )
    save_json(Path(args.output_json).resolve(), payload)

    print(f"Experiment:  {args.experiment_name}")
    print(f"Query ID:    {payload['query_id']}")
    print(f"Run ID:      {payload['run_id']}")
    print(f"Saved CSV:   {Path(args.output_csv).resolve()}")
    print(f"Saved JSON:  {Path(args.output_json).resolve()}")
    for row in payload["results"]:
        print(
            f"#{row['rank']} image_id={row['image_id']} species={row['species_name']} score={row['fused_score']:.6f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
