from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path
from typing import List

from PIL import Image
from tqdm import tqdm

from cub_utils import draw_bbox, locate_cub_root, normalize_image, write_csv

TRUTHY_VALUES = {"1", "true", "yes", "y", "keep", "x", "selected", "ok"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Normalize the manually selected CUB images into 224x224 bird crops."
    )
    parser.add_argument(
        "--selection-csv",
        default="outputs/review/candidates.csv",
        help="CSV generated by sample_candidates.py and annotated manually with keep=1.",
    )
    parser.add_argument(
        "--dataset-root",
        default="data/raw/cub2002011",
        help="Directory containing the extracted CUB dataset.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/processed",
        help="Directory for normalized images and exported metadata.",
    )
    parser.add_argument(
        "--padding-ratio",
        type=float,
        default=0.20,
        help="Extra padding added around the bounding box before square crop.",
    )
    parser.add_argument(
        "--target-size",
        type=int,
        default=224,
        help="Target width and height after resizing.",
    )
    parser.add_argument(
        "--max-images",
        type=int,
        default=1000,
        help="Maximum number of kept images allowed in the final export.",
    )
    parser.add_argument(
        "--require-count",
        type=int,
        default=0,
        help="If set, fail unless exactly this many images are marked keep=1.",
    )
    parser.add_argument(
        "--example-count",
        type=int,
        default=5,
        help="Number of intermediate examples to save for the report.",
    )
    parser.add_argument(
        "--clean-output",
        action="store_true",
        help="Delete old processed images, metadata, and intermediate examples before rebuilding.",
    )
    return parser.parse_args()


def truthy(value: str) -> bool:
    return str(value or "").strip().lower() in TRUTHY_VALUES


def is_keep_flag(value: str) -> bool:
    return truthy(value)


def parse_int_flag(value: str | int | float | None) -> int:
    if value is None:
        return 0
    raw = str(value).strip()
    if not raw:
        return 0
    if truthy(raw):
        return 1
    try:
        return int(float(raw))
    except ValueError:
        return 0


def derive_side_view(row: dict) -> int:
    one_eye_visible = parse_int_flag(row.get("one_eye_visible"))
    one_wing_visible = parse_int_flag(row.get("one_wing_visible"))
    bbox_horizontal = parse_int_flag(row.get("bbox_horizontal"))
    return int(one_eye_visible == 1 or one_wing_visible == 1 or bbox_horizontal == 1)


def resolve_source_path(dataset_root: Path, relative_image_path: str) -> Path:
    images_candidate = dataset_root / "images" / relative_image_path
    if images_candidate.exists():
        return images_candidate

    direct_candidate = dataset_root / relative_image_path
    if direct_candidate.exists():
        return direct_candidate

    raise FileNotFoundError(f"Unable to resolve source image: {relative_image_path}")


def load_selected_rows(selection_csv: Path) -> List[dict]:
    with selection_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        return [row for row in reader if is_keep_flag(row.get("keep", ""))]


def save_example_triplet(
    source_image: Image.Image,
    normalized_image: Image.Image,
    bbox,
    example_dir: Path,
    image_id: int,
) -> None:
    annotated = draw_bbox(source_image, bbox)
    annotated.save(example_dir / f"{image_id:05d}_original_with_bbox.jpg", quality=92)
    normalized_image.save(example_dir / f"{image_id:05d}_normalized_224.jpg", quality=92)

    left = annotated.copy()
    left.thumbnail((420, 420))
    right = normalized_image.copy()
    right.thumbnail((224, 224))
    canvas = Image.new("RGB", (left.width + right.width + 24, max(left.height, right.height) + 16), color="white")
    canvas.paste(left, (8, 8))
    canvas.paste(right, (left.width + 16, 8))
    canvas.save(example_dir / f"{image_id:05d}_panel.jpg", quality=92)


def main() -> int:
    args = parse_args()

    selection_csv = Path(args.selection_csv).resolve()
    dataset_root = locate_cub_root(Path(args.dataset_root).resolve())
    output_dir = Path(args.output_dir).resolve()
    images_output_dir = output_dir / "images"
    metadata_output_dir = output_dir / "metadata"
    examples_output_dir = Path("outputs/intermediate_examples").resolve()

    if args.clean_output:
        for target in (images_output_dir, metadata_output_dir, examples_output_dir):
            if target.exists():
                shutil.rmtree(target)

    images_output_dir.mkdir(parents=True, exist_ok=True)
    metadata_output_dir.mkdir(parents=True, exist_ok=True)
    examples_output_dir.mkdir(parents=True, exist_ok=True)

    selected_rows = load_selected_rows(selection_csv)
    if not selected_rows:
        raise ValueError("No rows marked keep=1 were found in the selection CSV.")

    if args.require_count and len(selected_rows) != args.require_count:
        raise ValueError(
            f"Expected exactly {args.require_count} kept images, but found {len(selected_rows)}."
        )

    if len(selected_rows) > args.max_images:
        raise ValueError(
            f"Found {len(selected_rows)} kept images, which exceeds the --max-images limit of {args.max_images}."
        )

    metadata_rows = []
    for index, row in enumerate(tqdm(selected_rows, desc="Normalizing selected images"), start=1):
        image_id = int(row["image_id"])
        source_path = resolve_source_path(dataset_root, row["relative_image_path"])
        bbox = (
            float(row["bbox_x"]),
            float(row["bbox_y"]),
            float(row["bbox_w"]),
            float(row["bbox_h"]),
        )

        with Image.open(source_path) as image:
            rgb_image = image.convert("RGB")
            normalized_image, crop_box = normalize_image(
                rgb_image,
                bbox,
                padding_ratio=args.padding_ratio,
                target_size=(args.target_size, args.target_size),
            )

            output_name = f"{image_id:05d}_{Path(row['relative_image_path']).stem}.jpg"
            output_path = images_output_dir / output_name
            normalized_image.save(output_path, quality=94)

            if index <= args.example_count:
                save_example_triplet(rgb_image, normalized_image, bbox, examples_output_dir, image_id)

            preprocess_params = {
                "method": "bbox_square_crop_then_resize",
                "padding_ratio": args.padding_ratio,
                "target_size": [args.target_size, args.target_size],
                "crop_box": list(crop_box),
                "bbox": [bbox[0], bbox[1], bbox[2], bbox[3]],
            }

            metadata_rows.append(
                {
                    "image_id": image_id,
                    "species_id": int(row["species_id"]),
                    "species_name": row["species_name"],
                    "split": row["split"],
                    "source_relative_path": row["relative_image_path"],
                    "processed_relative_path": str(output_path.relative_to(output_dir)),
                    "width": rgb_image.width,
                    "height": rgb_image.height,
                    "original_width": rgb_image.width,
                    "original_height": rgb_image.height,
                    "bbox_x": bbox[0],
                    "bbox_y": bbox[1],
                    "bbox_w": bbox[2],
                    "bbox_h": bbox[3],
                    "crop_left": crop_box[0],
                    "crop_top": crop_box[1],
                    "crop_right": crop_box[2],
                    "crop_bottom": crop_box[3],
                    "target_width": args.target_size,
                    "target_height": args.target_size,
                    "is_perching": parse_int_flag(row.get("perching_like")),
                    "is_side_view": derive_side_view(row),
                    "one_eye_visible": parse_int_flag(row.get("one_eye_visible")),
                    "one_wing_visible": parse_int_flag(row.get("one_wing_visible")),
                    "legs_visible": parse_int_flag(row.get("legs_visible")),
                    "bbox_horizontal": parse_int_flag(row.get("bbox_horizontal")),
                    "keep": "1",
                    "notes": row.get("notes", ""),
                    "preprocess_params": json.dumps(preprocess_params, ensure_ascii=True),
                }
            )

    fieldnames = [
        "image_id",
        "species_id",
        "species_name",
        "split",
        "source_relative_path",
        "processed_relative_path",
        "width",
        "height",
        "original_width",
        "original_height",
        "bbox_x",
        "bbox_y",
        "bbox_w",
        "bbox_h",
        "crop_left",
        "crop_top",
        "crop_right",
        "crop_bottom",
        "target_width",
        "target_height",
        "is_perching",
        "is_side_view",
        "one_eye_visible",
        "one_wing_visible",
        "legs_visible",
        "bbox_horizontal",
        "keep",
        "notes",
        "preprocess_params",
    ]
    write_csv(metadata_output_dir / "images.csv", metadata_rows, fieldnames)

    jsonl_path = metadata_output_dir / "images.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as handle:
        for row in metadata_rows:
            handle.write(json.dumps(row, ensure_ascii=True) + "\n")

    print(f"Normalized images:  {images_output_dir}")
    print(f"Metadata CSV:       {metadata_output_dir / 'images.csv'}")
    print(f"Metadata JSONL:     {jsonl_path}")
    print(f"Intermediate files: {examples_output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
