from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

import numpy as np

from feature_utils import load_csv_rows


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build SQLite database from extracted image features."
    )
    parser.add_argument(
        "--features-dir",
        default="data/features",
        help="Directory generated by extract_features.py.",
    )
    parser.add_argument(
        "--db-path",
        default="data/features/cbir_features.sqlite",
        help="SQLite database output path.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete existing database file before creating a new one.",
    )
    return parser.parse_args()


def create_schema(connection: sqlite3.Connection) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS images (
            image_id INTEGER PRIMARY KEY,
            species_id INTEGER NOT NULL,
            species_name TEXT NOT NULL,
            split TEXT,
            processed_relative_path TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS features (
            image_id INTEGER NOT NULL,
            feature_type TEXT NOT NULL,
            dim INTEGER NOT NULL,
            vector_json TEXT NOT NULL,
            PRIMARY KEY (image_id, feature_type),
            FOREIGN KEY (image_id) REFERENCES images(image_id)
        );

        CREATE TABLE IF NOT EXISTS retrieval_logs (
            log_id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at_utc TEXT NOT NULL,
            query_image_id INTEGER,
            mode TEXT NOT NULL,
            top_k INTEGER NOT NULL,
            scores_json TEXT NOT NULL
        );
        """
    )


def main() -> int:
    args = parse_args()

    features_dir = Path(args.features_dir).resolve()
    db_path = Path(args.db_path).resolve()

    if args.overwrite and db_path.exists():
        db_path.unlink()
    db_path.parent.mkdir(parents=True, exist_ok=True)

    manifest_rows = load_csv_rows(features_dir / "images_manifest.csv")
    cnn_matrix = np.load(features_dir / "cnn_embeddings.npy")
    hsv_matrix = np.load(features_dir / "hsv_histograms.npy")

    if len(manifest_rows) != cnn_matrix.shape[0] or len(manifest_rows) != hsv_matrix.shape[0]:
        raise ValueError("Manifest row count does not match feature matrix shape.")

    connection = sqlite3.connect(str(db_path))
    try:
        create_schema(connection)

        image_values = [
            (
                int(row["image_id"]),
                int(row["species_id"]),
                row["species_name"],
                row.get("split", ""),
                row["processed_relative_path"],
            )
            for row in manifest_rows
        ]
        connection.executemany(
            """
            INSERT OR REPLACE INTO images (
                image_id, species_id, species_name, split, processed_relative_path
            ) VALUES (?, ?, ?, ?, ?)
            """,
            image_values,
        )

        feature_values = []
        for index, row in enumerate(manifest_rows):
            image_id = int(row["image_id"])
            cnn_vector = cnn_matrix[index].astype(float).tolist()
            hsv_vector = hsv_matrix[index].astype(float).tolist()
            feature_values.append(
                (image_id, "cnn_embedding", int(len(cnn_vector)), json.dumps(cnn_vector, ensure_ascii=True))
            )
            feature_values.append(
                (image_id, "hsv_histogram", int(len(hsv_vector)), json.dumps(hsv_vector, ensure_ascii=True))
            )

        connection.executemany(
            """
            INSERT OR REPLACE INTO features (
                image_id, feature_type, dim, vector_json
            ) VALUES (?, ?, ?, ?)
            """,
            feature_values,
        )
        connection.commit()
    finally:
        connection.close()

    print(f"Built SQLite DB: {db_path}")
    print(f"Inserted images: {len(manifest_rows)}")
    print(f"Inserted features: {len(manifest_rows) * 2}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
