from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Tuple

import gradio as gr
import numpy as np
from PIL import Image

from feature_utils import (
    chi_square_similarity_scores,
    cosine_similarity_scores,
    extract_cnn_embedding,
    extract_hsv_histogram,
    load_cnn_model,
    load_csv_rows,
    load_json,
    parse_bins,
    resolve_processed_image_path,
    select_device,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Launch a Gradio demo UI for CBIR top-k image retrieval."
    )
    parser.add_argument(
        "--features-dir",
        default="data/features",
        help="Directory generated by extract_features.py.",
    )
    parser.add_argument(
        "--processed-root",
        default="data/processed",
        help="Root path to normalized images.",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Inference device for CNN query embedding.",
    )
    parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Host address for Gradio server.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=7860,
        help="Port for Gradio server.",
    )
    parser.add_argument(
        "--share",
        action="store_true",
        help="Enable Gradio share link.",
    )
    return parser.parse_args()


class RetrievalEngine:
    def __init__(self, features_dir: Path, processed_root: Path, device_name: str) -> None:
        self.features_dir = features_dir.resolve()
        self.processed_root = processed_root.resolve()
        self.device = select_device(device_name)

        self.config = load_json(self.features_dir / "config.json")
        self.bins = parse_bins(",".join(str(value) for value in self.config["hsv_bins"]))
        self.manifest_rows = load_csv_rows(self.features_dir / "images_manifest.csv")
        self.cnn_matrix = np.load(self.features_dir / "cnn_embeddings.npy")
        self.hsv_matrix = np.load(self.features_dir / "hsv_histograms.npy")

        if len(self.manifest_rows) != self.cnn_matrix.shape[0] or len(self.manifest_rows) != self.hsv_matrix.shape[0]:
            raise ValueError("Feature matrix row count does not match images_manifest.csv.")

        self.cnn_model = None

    def _load_model_if_needed(self) -> None:
        if self.cnn_model is None:
            self.cnn_model = load_cnn_model(self.config["cnn_backbone"], self.device)

    def _build_scores(
        self,
        mode: str,
        query_cnn,
        query_hsv,
        w_cnn: float,
        w_hsv: float,
    ) -> np.ndarray:
        if mode == "cnn":
            if query_cnn is None:
                raise ValueError("CNN query vector is required for mode=cnn.")
            return cosine_similarity_scores(query_cnn, self.cnn_matrix)

        if mode == "hsv":
            if query_hsv is None:
                raise ValueError("HSV query vector is required for mode=hsv.")
            return chi_square_similarity_scores(query_hsv, self.hsv_matrix)

        if query_cnn is None or query_hsv is None:
            raise ValueError("Both CNN and HSV query vectors are required for mode=fusion.")
        cnn_scores = cosine_similarity_scores(query_cnn, self.cnn_matrix)
        hsv_scores = chi_square_similarity_scores(query_hsv, self.hsv_matrix)
        return (w_cnn * cnn_scores) + (w_hsv * hsv_scores)

    def query(
        self,
        query_image,
        mode: str,
        top_k: int,
        w_cnn: float,
        w_hsv: float,
    ) -> Tuple[List[Tuple[Image.Image, str]], List[dict]]:
        if query_image is None:
            return [], []

        rgb_image = query_image.convert("RGB")
        query_hsv = extract_hsv_histogram(rgb_image, bins=self.bins) if mode in {"hsv", "fusion"} else None
        query_cnn = None
        if mode in {"cnn", "fusion"}:
            self._load_model_if_needed()
            query_cnn = extract_cnn_embedding(self.cnn_model, rgb_image, self.device)

        scores = self._build_scores(
            mode=mode,
            query_cnn=query_cnn,
            query_hsv=query_hsv,
            w_cnn=w_cnn,
            w_hsv=w_hsv,
        )

        ranked_indices = np.argsort(-scores)[: max(top_k, 1)]
        gallery_items: List[Tuple[Image.Image, str]] = []
        table_rows: List[dict] = []

        for rank, index in enumerate(ranked_indices, start=1):
            row = self.manifest_rows[index]
            image_path = resolve_processed_image_path(row, self.processed_root)
            with Image.open(image_path) as image:
                result_image = image.convert("RGB").copy()

            caption = f"#{rank} | id={row['image_id']} | {row['species_name']} | score={float(scores[index]):.4f}"
            gallery_items.append((result_image, caption))
            table_rows.append(
                {
                    "rank": rank,
                    "image_id": int(row["image_id"]),
                    "species_id": int(row["species_id"]),
                    "species_name": row["species_name"],
                    "score": float(scores[index]),
                }
            )

        return gallery_items, table_rows


def build_app(engine: RetrievalEngine) -> gr.Blocks:
    with gr.Blocks(title="Bird CBIR Demo", theme=gr.themes.Soft()) as app:
        gr.Markdown("# Bird CBIR Retrieval Demo")
        gr.Markdown("Upload a query image, choose retrieval mode, and return top-k similar birds.")

        with gr.Row():
            query_input = gr.Image(label="Query Image", type="pil")
            with gr.Column():
                mode_input = gr.Radio(
                    choices=["fusion", "cnn", "hsv"],
                    value="fusion",
                    label="Retrieval Mode",
                )
                topk_input = gr.Slider(1, 20, value=5, step=1, label="Top K")
                w_cnn_input = gr.Slider(0.0, 1.0, value=0.7, step=0.05, label="Fusion Weight - CNN")
                w_hsv_input = gr.Slider(0.0, 1.0, value=0.3, step=0.05, label="Fusion Weight - HSV")
                run_btn = gr.Button("Run Retrieval", variant="primary")

        gallery_output = gr.Gallery(
            label="Top-K Results",
            columns=5,
            rows=1,
            object_fit="contain",
            height=360,
        )
        table_output = gr.JSON(label="Ranked Scores")

        def _run(query_image, mode, top_k, w_cnn, w_hsv):
            gallery, rows = engine.query(query_image, mode, int(top_k), float(w_cnn), float(w_hsv))
            return gallery, rows

        run_btn.click(
            fn=_run,
            inputs=[query_input, mode_input, topk_input, w_cnn_input, w_hsv_input],
            outputs=[gallery_output, table_output],
        )

    return app


def main() -> int:
    args = parse_args()
    engine = RetrievalEngine(
        features_dir=Path(args.features_dir),
        processed_root=Path(args.processed_root),
        device_name=args.device,
    )
    app = build_app(engine)
    app.launch(server_name=args.host, server_port=args.port, share=args.share)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
