from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import numpy as np

from feature_utils import (
    chi_square_similarity_scores,
    cosine_similarity_scores,
    load_csv_rows,
    load_json,
    save_json,
    write_csv_rows,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate retrieval quality with Precision@K."
    )
    parser.add_argument(
        "--features-dir",
        default="data/features",
        help="Directory generated by extract_features.py.",
    )
    parser.add_argument(
        "--mode",
        choices=("cnn", "hsv", "fusion"),
        default="fusion",
        help="Feature mode for scoring.",
    )
    parser.add_argument(
        "--k",
        type=int,
        default=5,
        help="Top-K cutoff for Precision@K.",
    )
    parser.add_argument(
        "--w-cnn",
        type=float,
        default=0.7,
        help="Fusion weight for CNN similarity when mode=fusion.",
    )
    parser.add_argument(
        "--w-hsv",
        type=float,
        default=0.3,
        help="Fusion weight for HSV similarity when mode=fusion.",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/eval",
        help="Directory to save evaluation reports.",
    )
    return parser.parse_args()


def _compute_scores(
    mode: str,
    query_index: int,
    cnn_matrix: np.ndarray,
    hsv_matrix: np.ndarray,
    w_cnn: float,
    w_hsv: float,
) -> np.ndarray:
    if mode == "cnn":
        return cosine_similarity_scores(cnn_matrix[query_index], cnn_matrix)
    if mode == "hsv":
        return chi_square_similarity_scores(hsv_matrix[query_index], hsv_matrix)

    cnn_scores = cosine_similarity_scores(cnn_matrix[query_index], cnn_matrix)
    hsv_scores = chi_square_similarity_scores(hsv_matrix[query_index], hsv_matrix)
    return (w_cnn * cnn_scores) + (w_hsv * hsv_scores)


def main() -> int:
    args = parse_args()

    features_dir = Path(args.features_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_rows = load_csv_rows(features_dir / "images_manifest.csv")
    if not manifest_rows:
        raise ValueError("images_manifest.csv is empty.")

    _ = load_json(features_dir / "config.json")
    cnn_matrix = np.load(features_dir / "cnn_embeddings.npy")
    hsv_matrix = np.load(features_dir / "hsv_histograms.npy")

    if len(manifest_rows) != cnn_matrix.shape[0] or len(manifest_rows) != hsv_matrix.shape[0]:
        raise ValueError("Manifest row count does not match feature matrix shape.")

    species_ids = np.array([int(row["species_id"]) for row in manifest_rows], dtype=np.int32)
    image_ids = np.array([int(row["image_id"]) for row in manifest_rows], dtype=np.int32)

    per_query_rows: List[dict] = []
    precisions = []
    for query_index in range(len(manifest_rows)):
        query_id = int(image_ids[query_index])
        query_species_id = int(species_ids[query_index])

        scores = _compute_scores(
            mode=args.mode,
            query_index=query_index,
            cnn_matrix=cnn_matrix,
            hsv_matrix=hsv_matrix,
            w_cnn=args.w_cnn,
            w_hsv=args.w_hsv,
        )
        scores[query_index] = -np.inf
        ranked = np.argsort(-scores)[: args.k]

        relevant = int(np.sum(species_ids[ranked] == query_species_id))
        precision = float(relevant / max(args.k, 1))
        precisions.append(precision)
        per_query_rows.append(
            {
                "query_image_id": query_id,
                "query_species_id": query_species_id,
                "relevant_in_topk": relevant,
                "precision_at_k": precision,
            }
        )

    mean_precision = float(np.mean(precisions)) if precisions else 0.0

    per_query_csv = output_dir / f"precision_at_{args.k}_per_query_{args.mode}.csv"
    summary_json = output_dir / f"precision_at_{args.k}_summary_{args.mode}.json"

    write_csv_rows(
        per_query_csv,
        per_query_rows,
        fieldnames=["query_image_id", "query_species_id", "relevant_in_topk", "precision_at_k"],
    )
    save_json(
        summary_json,
        {
            "mode": args.mode,
            "k": args.k,
            "num_queries": len(per_query_rows),
            "mean_precision_at_k": mean_precision,
            "w_cnn": args.w_cnn,
            "w_hsv": args.w_hsv,
        },
    )

    print(f"Mode: {args.mode}")
    print(f"K: {args.k}")
    print(f"Queries: {len(per_query_rows)}")
    print(f"Mean Precision@{args.k}: {mean_precision:.6f}")
    print(f"Saved per-query CSV: {per_query_csv}")
    print(f"Saved summary JSON:  {summary_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
