from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import List

import numpy as np
from PIL import Image
from tqdm import tqdm

from feature_utils import (
    extract_cnn_embedding,
    extract_hsv_histogram,
    load_cnn_model,
    load_csv_rows,
    parse_bins,
    resolve_processed_image_path,
    save_json,
    select_device,
    write_csv_rows,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract CNN embeddings and HSV histograms for normalized bird images."
    )
    parser.add_argument(
        "--metadata-csv",
        default="data/processed/metadata/images.csv",
        help="Path to normalized metadata CSV generated by normalize_selected.py.",
    )
    parser.add_argument(
        "--processed-root",
        default="data/processed",
        help="Root directory that contains normalized images referenced by metadata.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/features",
        help="Directory to save extracted feature artifacts.",
    )
    parser.add_argument(
        "--cnn-backbone",
        choices=("resnet18", "resnet50"),
        default="resnet18",
        help="Pretrained CNN backbone used for embedding extraction.",
    )
    parser.add_argument(
        "--hsv-bins",
        default="8,8,8",
        help="Histogram bins in format h,s,v (example: 8,8,8).",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Execution device for CNN extraction.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    metadata_csv = Path(args.metadata_csv).resolve()
    processed_root = Path(args.processed_root).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_csv_rows(metadata_csv)
    if not rows:
        raise ValueError(f"No rows found in metadata CSV: {metadata_csv}")

    bins = parse_bins(args.hsv_bins)
    device = select_device(args.device)
    model = load_cnn_model(args.cnn_backbone, device)

    cnn_vectors: List[np.ndarray] = []
    hsv_vectors: List[np.ndarray] = []
    manifest_rows = []

    for row in tqdm(rows, desc="Extracting features"):
        image_path = resolve_processed_image_path(row, processed_root)
        with Image.open(image_path) as image:
            rgb_image = image.convert("RGB")
            cnn_vector = extract_cnn_embedding(model, rgb_image, device)
            hsv_vector = extract_hsv_histogram(rgb_image, bins=bins)

        cnn_vectors.append(cnn_vector)
        hsv_vectors.append(hsv_vector)
        manifest_rows.append(
            {
                "image_id": int(row["image_id"]),
                "species_id": int(row["species_id"]),
                "species_name": row["species_name"],
                "split": row.get("split", ""),
                "processed_relative_path": row.get("processed_relative_path", ""),
            }
        )

    cnn_matrix = np.vstack(cnn_vectors).astype(np.float32)
    hsv_matrix = np.vstack(hsv_vectors).astype(np.float32)

    np.save(output_dir / "cnn_embeddings.npy", cnn_matrix)
    np.save(output_dir / "hsv_histograms.npy", hsv_matrix)

    write_csv_rows(
        output_dir / "images_manifest.csv",
        manifest_rows,
        fieldnames=["image_id", "species_id", "species_name", "split", "processed_relative_path"],
    )

    features_jsonl = output_dir / "features.jsonl"
    with features_jsonl.open("w", encoding="utf-8") as handle:
        for idx, row in enumerate(manifest_rows):
            payload = {
                "image_id": row["image_id"],
                "cnn_embedding": cnn_matrix[idx].tolist(),
                "hsv_histogram": hsv_matrix[idx].tolist(),
            }
            handle.write(json.dumps(payload, ensure_ascii=True) + "\n")

    save_json(
        output_dir / "config.json",
        {
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "metadata_csv": str(metadata_csv),
            "processed_root": str(processed_root),
            "cnn_backbone": args.cnn_backbone,
            "hsv_bins": list(bins),
            "cnn_dim": int(cnn_matrix.shape[1]),
            "hsv_dim": int(hsv_matrix.shape[1]),
            "num_images": int(cnn_matrix.shape[0]),
            "device_used": str(device),
        },
    )

    print(f"Saved manifest:        {output_dir / 'images_manifest.csv'}")
    print(f"Saved CNN embeddings:  {output_dir / 'cnn_embeddings.npy'}")
    print(f"Saved HSV histograms:  {output_dir / 'hsv_histograms.npy'}")
    print(f"Saved feature JSONL:   {features_jsonl}")
    print(f"Saved config:          {output_dir / 'config.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
