from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import numpy as np
from PIL import Image

from feature_utils import (
    chi_square_similarity_scores,
    cosine_similarity_scores,
    extract_cnn_embedding,
    extract_hsv_histogram,
    index_by_image_id,
    load_cnn_model,
    load_csv_rows,
    load_json,
    parse_bins,
    resolve_processed_image_path,
    select_device,
    write_csv_rows,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run top-k retrieval with CNN, HSV, or fusion features."
    )
    parser.add_argument(
        "--features-dir",
        default="data/features",
        help="Directory generated by extract_features.py.",
    )
    parser.add_argument(
        "--processed-root",
        default="data/processed",
        help="Root folder for processed images in case query by image_id needs file access.",
    )
    parser.add_argument(
        "--query-image-id",
        type=int,
        default=0,
        help="Existing image_id from manifest to use as query.",
    )
    parser.add_argument(
        "--query-image-path",
        default="",
        help="External query image path. If set, this is used instead of --query-image-id.",
    )
    parser.add_argument(
        "--mode",
        choices=("cnn", "hsv", "fusion"),
        default="fusion",
        help="Feature mode for retrieval scoring.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of top results to return.",
    )
    parser.add_argument(
        "--w-cnn",
        type=float,
        default=0.7,
        help="Fusion weight for CNN similarity when mode=fusion.",
    )
    parser.add_argument(
        "--w-hsv",
        type=float,
        default=0.3,
        help="Fusion weight for HSV similarity when mode=fusion.",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Execution device when query-image-path requires CNN extraction.",
    )
    parser.add_argument(
        "--output-csv",
        default="outputs/retrieval/topk_results.csv",
        help="Path to save ranked retrieval results.",
    )
    return parser.parse_args()


def _build_scores(
    mode: str,
    cnn_matrix: np.ndarray,
    hsv_matrix: np.ndarray,
    query_cnn: np.ndarray | None,
    query_hsv: np.ndarray | None,
    w_cnn: float,
    w_hsv: float,
) -> np.ndarray:
    if mode == "cnn":
        if query_cnn is None:
            raise ValueError("CNN query vector is required for mode=cnn.")
        return cosine_similarity_scores(query_cnn, cnn_matrix)

    if mode == "hsv":
        if query_hsv is None:
            raise ValueError("HSV query vector is required for mode=hsv.")
        return chi_square_similarity_scores(query_hsv, hsv_matrix)

    if query_cnn is None or query_hsv is None:
        raise ValueError("Both CNN and HSV query vectors are required for mode=fusion.")
    cnn_scores = cosine_similarity_scores(query_cnn, cnn_matrix)
    hsv_scores = chi_square_similarity_scores(query_hsv, hsv_matrix)
    return (w_cnn * cnn_scores) + (w_hsv * hsv_scores)


def main() -> int:
    args = parse_args()

    features_dir = Path(args.features_dir).resolve()
    processed_root = Path(args.processed_root).resolve()
    output_csv = Path(args.output_csv).resolve()

    config = load_json(features_dir / "config.json")
    bins = parse_bins(",".join(str(value) for value in config["hsv_bins"]))

    manifest_rows = load_csv_rows(features_dir / "images_manifest.csv")
    if not manifest_rows:
        raise ValueError("images_manifest.csv is empty.")

    image_id_to_index = index_by_image_id(manifest_rows)
    cnn_matrix = np.load(features_dir / "cnn_embeddings.npy")
    hsv_matrix = np.load(features_dir / "hsv_histograms.npy")

    if cnn_matrix.shape[0] != len(manifest_rows) or hsv_matrix.shape[0] != len(manifest_rows):
        raise ValueError("Feature matrix row count does not match images_manifest.csv.")

    query_index = None
    query_id = None
    query_cnn = None
    query_hsv = None

    if args.query_image_path:
        query_path = Path(args.query_image_path).resolve()
        if not query_path.exists():
            raise FileNotFoundError(f"Query image not found: {query_path}")
        with Image.open(query_path) as image:
            rgb_image = image.convert("RGB")
            query_hsv = extract_hsv_histogram(rgb_image, bins=bins)
            if args.mode in {"cnn", "fusion"}:
                device = select_device(args.device)
                model = load_cnn_model(config["cnn_backbone"], device)
                query_cnn = extract_cnn_embedding(model, rgb_image, device)
    else:
        if args.query_image_id <= 0:
            raise ValueError("Provide --query-image-id or --query-image-path.")
        query_id = args.query_image_id
        if query_id not in image_id_to_index:
            raise ValueError(f"query_image_id {query_id} not found in images_manifest.csv.")
        query_index = image_id_to_index[query_id]
        query_cnn = cnn_matrix[query_index]
        query_hsv = hsv_matrix[query_index]

        if args.mode in {"cnn", "fusion"}:
            row = manifest_rows[query_index]
            _ = resolve_processed_image_path(row, processed_root)

    scores = _build_scores(
        mode=args.mode,
        cnn_matrix=cnn_matrix,
        hsv_matrix=hsv_matrix,
        query_cnn=query_cnn,
        query_hsv=query_hsv,
        w_cnn=args.w_cnn,
        w_hsv=args.w_hsv,
    )

    ranked_indices = np.argsort(-scores)
    result_rows: List[dict] = []
    rank = 1
    for index in ranked_indices:
        if query_index is not None and index == query_index:
            continue
        row = manifest_rows[index]
        result_rows.append(
            {
                "rank": rank,
                "image_id": int(row["image_id"]),
                "species_id": int(row["species_id"]),
                "species_name": row["species_name"],
                "processed_relative_path": row["processed_relative_path"],
                "score": float(scores[index]),
            }
        )
        rank += 1
        if len(result_rows) >= args.top_k:
            break

    write_csv_rows(
        output_csv,
        result_rows,
        fieldnames=["rank", "image_id", "species_id", "species_name", "processed_relative_path", "score"],
    )

    print(f"Saved retrieval results: {output_csv}")
    for row in result_rows:
        print(
            f"#{row['rank']} image_id={row['image_id']} species={row['species_name']} score={row['score']:.6f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
